// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsAukEW0HjV4z-58SlLoToXNE6yXZNaDk',
    appId: '1:940032387389:web:76aa0cb3bc5da04bb7bd54',
    messagingSenderId: '940032387389',
    projectId: 'resturantapp-a6df7',
    authDomain: 'resturantapp-a6df7.firebaseapp.com',
    storageBucket: 'resturantapp-a6df7.appspot.com',
    measurementId: 'G-T0ZZGK4Q5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BgyRzBAKGmUmEFGQZkNlP2DMvPh3GgM',
    appId: '1:940032387389:android:ac02857c4c75cd29b7bd54',
    messagingSenderId: '940032387389',
    projectId: 'resturantapp-a6df7',
    storageBucket: 'resturantapp-a6df7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5exg8IedzTCgj-IGu5HVMjQRyWOFOU8',
    appId: '1:940032387389:ios:c86a69e0d49f9af8b7bd54',
    messagingSenderId: '940032387389',
    projectId: 'resturantapp-a6df7',
    storageBucket: 'resturantapp-a6df7.appspot.com',
    iosClientId: '940032387389-58adub0872ooa504rd4hbrhidm8i80ub.apps.googleusercontent.com',
    iosBundleId: 'com.wappnet.tableMenuCustomer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw5exg8IedzTCgj-IGu5HVMjQRyWOFOU8',
    appId: '1:940032387389:ios:c86a69e0d49f9af8b7bd54',
    messagingSenderId: '940032387389',
    projectId: 'resturantapp-a6df7',
    storageBucket: 'resturantapp-a6df7.appspot.com',
    iosClientId: '940032387389-58adub0872ooa504rd4hbrhidm8i80ub.apps.googleusercontent.com',
    iosBundleId: 'com.wappnet.tableMenuCustomer',
  );
}
